"use strict";
/*
    Constants to store all error number and error message
*/
const MESSAGES = {
    "98": "JSON data is in valid",
    "99": "Phone is empty",
    "100": "Email is empty",
    "101": "Email or Phone is required",
    "102": "Email is not valid",
    "103": "Phone is invalid",
    "104": "Password is empty",
    "105": "Passwrod must be between {{start}} and {{end}}",
    "1051": "",
    "106": "Confirmed password is empty",
    "107": "Password and confirmed password are not matched",
    "108": "Invalid password.",
    "109": "Account does not exist or is not activated",
    "110": "Both phone and email are not valid",
    "111": "Password must contain at least one",
    "1111": "of these special characters !,@,#,$,*",
    "1112": "alphabet",
    "1113": "number",
    "113": "Account already exists",
    "114": "Account already exists",
    "115": "Account already exists",
    "SuccessLoggedIn": "Successfully logged in",
    "SuccessLoggedOut": "Successfuly logged out",
    "Verified": "Account has been verified",
    "NotVerified": "Account has yet been verified",
    "Registered": "Successfully registered",
    "UpdatedPassword": "Successfully updated password",
    "NotAuthenticated": "Not authenticated",
    "ExpiredAccessToken": "Access token is expired",
    "InvalidAccessToken": "Access token is invalid",
    "ExpiredRefreshToken": "Refresh token is expired",
    "InvalidRefreshToken": "Refresh token is invalid",
    "InternalServerError": "Internal Server Error",
    "BadRequest": "Bad request",
    "InvalidVerifiedCode": "Invalid verification code",
    "RequiredToken": "Token is required",
    "ItemIsExisted": "This item is already existed",
    "RequiredField": "Required field is not supplied",
    "SuccessfulAdded": "This item is successfully added",
    "GenericError": "Something went wrong",
    "SuccessfulUpdated": "This item is successfully updated",
    "SuccessfullyRetrieved": "Items are successfully retrieved",
    "SuccessfulDeleted": "This item is successfuly deleted",
    "CodeRefreshed": "Registration code has been refreshed"
};
module.exports = MESSAGES;
